name: Java Banking Dashboard application

on:
  push:
    branches:
      - 

jobs:

  # 1. Build Job
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.1.0

      - name: Setup Java 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'

      - name: Check Java version
        run: java --version

      - name: Build and Test
        run: mvn clean verify


  # 2. SonarQube Job
  sonarqube:
    name: SonarQube Analysis
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.1.0

      - name: Setup Java 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'

      - name: SonarQube Analysis and Quality Gate
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=java-project \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true


  # 3. Nexus Job
  nexus:
    name: Publish JAR to Nexus
    needs: sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.1.0

      - name: Setup Java 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'

      - name: Configure Maven credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus-releases</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Publish JAR to Nexus
        run: mvn deploy


  # 4. Docker + Trivy + ECR Job
  docker-security:
    name: Docker Build, Trivy Scan and ECR Push
    needs: nexus
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v6.1.0

      - name: Download JAR from Nexus
        run: |
          curl -f -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" \
            -o java-build-dashboard.jar \
            "http://13.206.101.224:8081/repository/maven-releases-java-project/com/example/java-build-dashboard/1.0.0/java-build-dashboard-1.0.0.jar"

      - name: Verify JAR
        run: |
          ls -lh java-build-dashboard.jar

      - name: Build Docker image
        run: |
          docker build -t java-build-dashboard:${{ github.sha }} .

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: java-build-dashboard:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      # 5. Configure AWS credentials using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      # 6. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 7. Tag and Push Docker image to ECR
      - name: Push Docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: java-build-dashboard
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag java-build-dashboard:${IMAGE_TAG} \
            ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

          docker push \
            ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

  #Image updat helm job
  update-helm:
      name: Update Helm Image tag
      needs: docker-security
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        - name: Checkout code
          uses: actions/checkout@v6.1.0
        - name: Update image tag in Helm values
          run: |
            sed -i "s/^  tag: .*/  tag: \"${GITHUB_SHA}\"/" java-build-dashboard/values.yaml  

        - name: Show updated values
          run: |
            grep -A4 "^image:" java-build-dashboard/values.yaml  

        - name: Commit and push Helm change
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"  

            git add java-build-dashboard/values.yaml
            git commit -m "chore: update image tag to ${GITHUB_SHA} [skip ci]" || echo "No changes to commit"
            git push  