name: Java Banking Dashboard application

on:
  push:
    branches:
      - main

jobs:

  # 1. Build job
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.1.0

      - name: Setup Java 11
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '11'

      - name: Check Java version
        run: java --version

      - name: Build and Test
        run: mvn clean verify


  # 2. SonarQube job
  sonarqube:
    name: SonarQube Analysis
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.1.0

      - name: Setup Java 11
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '11'

      - name: SonarQube Analysis and Quality Gate
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=java-project \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true


  # 3. Nexus job
  nexus:
    name: Publish JAR to Nexus
    needs: sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.1.0

      - name: Setup Java 11
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '11'

      - name: Configure Maven credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus-releases</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Publish JAR to Nexus
        run: mvn deploy
