name: Java Banking Dashboard application
on:
  push:
    branches:
      - main
jobs:
#1.this is build job
   build:
     name: Build and Test
     runs-on: ubuntu-latest
     steps:
      - name: checkout code 
        uses: actions/checkout@v6.1.0

      - name: Setup java 11
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '11'

      - name: check java version
        run: java --version
      
        #Here we do clean package and test instead of like this in companies give direct single step
        #that is mvn clean verify it will do both
        # - name: Build
        # run: mvn clean package -DskipTests
        # - name: Unit Test
        # run: mvn test

      - name: Build and Test
        run: mvn clean verify
#2.sonarqube job
   sonarqube:
     name: sonarqube Analysis
     needs: build
     runs-on: ubuntu-latest 
     steps:
      - name: checkout code 
        uses: actions/checkout@v6.1.0

      - name: Setup java 11
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '11'
      - name: SonarQube Analysis and Quality Gate
        run: | 
         mvn sonar:sonar \
            -Dsonar.projectKey=java-project \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true

#3.Nexus Job
    nexus:
      name: Publish Jar to Nexus
      needs: sonarqube
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v6.1.0

      - name: Setup Java 11
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '11'

      - name: Configure Maven credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus-releases</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Publish JAR to Nexus
        run: mvn deploy

     
   
